name: banshan-login
version: '1.0'
main: asia.yinshaoze.login.Banshanlogin
author: 'yinshaoze'
commands:
  login:
    description: '半山模块 登录注册命令'
    permission: 'bs.login.use'
    permission-message: '缺少bs.login.use权限'
    usage: /<command> l/r YOUR_PASSWORD